#!/usr/bin/env bash

echo "Building image: $IMAGE_NAME"

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name multiarch --driver docker-container --use
docker buildx inspect --bootstrap

docker buildx build --platform=linux/arm64,linux/amd64 -t "$IMAGE_NAME" -f "$DOCKERFILE_PATH" .
