#!/usr/bin/env bash
docker build --push --platform=linux/amd64 -t "$IMAGE_NAME-amd64" -f "$DOCKERFILE_PATH" .
docker build --push --platform=linux/arm64 -t "$IMAGE_NAME-arm64" -f "$DOCKERFILE_PATH" .
docker manifest create "$IMAGE_NAME" "$IMAGE_NAME-amd64" "$IMAGE_NAME-arm64"
docker manifest push "$IMAGE_NAME"
